🔀 :: 깃랭크 SecurityConfig 수정
team-xquare/v1-service-git pull request #10
Opened 2023-06-29 05:20 UTC by jaemin05

이유
• .authenticated() 으로 할 경우 httpBasic과 formLogin이 disable이 먹히지 않아서 수정하였습니다.
![image](https://github.com/team-xquare/v1-service-git/assets/89118999/0038a529-1431-49f5-9c32-0a64896bf081)

한 일
• permitAll로 수정

2023-06-29 08:23 UTC, jungho1209 approved these changes

2023-06-29 14:20 UTC, leeseojune53 requested changes
음.. 일단 anyExchange부분을 permitAll로 푸는건 위험해 보입니다. 
https://stackoverflow.com/questions/69615309/disable-sign-in-window-in-spring-http-basic 요런 것도 있네요 한 번 확인 부탁드립니다

2023-06-30 14:34 UTC, leeseojune53 approved these changes
LGTM :)

2023-07-01 07:46 UTC, jaemin05 commented
> 음.. 일단 anyExchange부분을 permitAll로 푸는건 위험해 보입니다. https://stackoverflow.com/questions/69615309/disable-sign-in-window-in-spring-http-basic 요런 것도 있네요 한 번 확인 부탁드립니다

authenticationEntryPoint을 이용해서 
![image](https://github.com/team-xquare/v1-service-git/assets/89118999/8221103d-07d2-4f12-b5cc-f5b3195a2b12)

2023-07-01 07:46 UTC, merged